name: Add Media From Short

on:
  workflow_dispatch:
    inputs:
      media_type:
        description: 'Media Type'
        required: true
      media_title:
        description: 'Media Title'
        required: true

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Send Inputs to GitHub Summary
      run: |
        echo "### Workflow Inputs" >> $GITHUB_STEP_SUMMARY
        echo "- Media Type: ${{ github.event.inputs.media_type }}" >> $GITHUB_STEP_SUMMARY
        echo "- Media Title: ${{ github.event.inputs.media_title }}" >> $GITHUB_STEP_SUMMARY

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        # cache: 'pip' # caching pip dependencies

    - name: Install Python Dependencies
      run: |
        pip install openai

    - name: Run Python Script
      working-directory: ./scripts
      run: |
        python ./genMediaJSON.py --media_type "${{ github.event.inputs.media_type }}" --title "${{ github.event.inputs.media_title }}" --proceed
  
    - name: Check for JSON Errors
      working-directory: ./scripts
      run: |
        python ./checkJSON.py

    - name: Commit Changes
      run: |
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
        git add .
        git commit -m "Added the ${{github.event.inputs.media_type}} ${{ github.event.inputs.media_title }} to the media Database"
        git push