# This is a basic workflow to help you get started with Actions
name: Build and Deploy App Frontend and Backend

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  workflow_dispatch

env:
  AWS_REGION : us-east-1 #Change to reflect your Region

# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  buildAndDeployPersistent:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Persistent Infra Dependencies
        run: npm install
        working-directory: app/persistentInfra

      - name: Build CDK
        run: npm run build
        working-directory: app/persistentInfra

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::xxxx:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
  
      - name: Synth Infra
        run: npm run synth
        working-directory: app/persistentInfra

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Deploy Infra
        run: npm run deploy
        working-directory: app/persistentInfra